services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

volumes:
  frontend_node_modules:
